const flashcardsData = {
  "서론": [
    { front: "Anatomy", back: "해부학", desc: "신체 구조를 연구하는 학문 (예시 )" },
    { front: "Physiology", back: "생리학", desc: "신체 기능을 연구하는 학문 (예시 )" },
    { front: "Homeostasis", back: "항상성", desc: "신체 내부 환경을 일정하게 유지 (예시 )" },
    { front: "Anatomy", back: "해부학", desc: "신체 구조를 연구하는 학문 (예시 )" },
    { front: "Physiology", back: "생리학", desc: "신체 기능을 연구하는 학문 (예시 )" },
    { front: "Homeostasis", back: "항상성", desc: "신체 내부 환경을 일정하게 유지 (예시 )" },
    { front: "Anatomy", back: "해부학", desc: "신체 구조를 연구하는 학문 (예시 )" },
    { front: "Physiology", back: "생리학", desc: "신체 기능을 연구하는 학문 (예시 )" },
    { front: "Homeostasis", back: "항상성", desc: "신체 내부 환경을 일정하게 유지 (예시 )" },
    { front: "Anatomy", back: "해부학", desc: "신체 구조를 연구하는 학문 (예시 )" },
    { front: "Physiology", back: "생리학", desc: "신체 기능을 연구하는 학문 (예시 )" },
    { front: "Homeostasis", back: "항상성", desc: "신체 내부 환경을 일정하게 유지 (예시 )" },
    { front: "Anatomy", back: "해부학", desc: "신체 구조를 연구하는 학문 (예시 )" },
    { front: "Physiology", back: "생리학", desc: "신체 기능을 연구하는 학문 (예시 )" },
    { front: "Homeostasis", back: "항상성", desc: "신체 내부 환경을 일정하게 유지 (예시 )" },
    { front: "Anatomy", back: "해부학", desc: "신체 구조를 연구하는 학문 (예시 )" },
    { front: "Physiology", back: "생리학", desc: "신체 기능을 연구하는 학문 (예시 )" },
    { front: "Homeostasis", back: "항상성", desc: "신체 내부 환경을 일정하게 유지 (예시 )" },
    { front: "Anatomy", back: "해부학", desc: "신체 구조를 연구하는 학문 (예시 )" },
    { front: "Physiology", back: "생리학", desc: "신체 기능을 연구하는 학문 (예시 )" },
    { front: "Homeostasis", back: "항상성", desc: "신체 내부 환경을 일정하게 유지 (예시 )" },
    { front: "Anatomy", back: "해부학", desc: "신체 구조를 연구하는 학문 (예시 )" },
    { front: "Physiology", back: "생리학", desc: "신체 기능을 연구하는 학문 (예시 )" },
    { front: "Homeostasis", back: "항상성", desc: "신체 내부 환경을 일정하게 유지 (예시 )" },
    { front: "Anatomy", back: "해부학", desc: "신체 구조를 연구하는 학문 (예시 )" },
    { front: "Physiology", back: "생리학", desc: "신체 기능을 연구하는 학문 (예시 )" },
    { front: "Homeostasis", back: "항상성", desc: "신체 내부 환경을 일정하게 유지 (예시 )" },
    { front: "Anatomy", back: "해부학", desc: "신체 구조를 연구하는 학문 (예시 )" },
    { front: "Physiology", back: "생리학", desc: "신체 기능을 연구하는 학문 (예시 )" },
    { front: "Homeostasis", back: "항상성", desc: "신체 내부 환경을 일정하게 유지 (예시 )" },
    { front: "Anatomy", back: "해부학", desc: "신체 구조를 연구하는 학문 (예시 )" },
    { front: "Physiology", back: "생리학", desc: "신체 기능을 연구하는 학문 (예시 )" },
    { front: "Homeostasis", back: "항상성", desc: "신체 내부 환경을 일정하게 유지 (예시 )" },
    { front: "Anatomy", back: "해부학", desc: "신체 구조를 연구하는 학문 (예시 )" },
    { front: "Physiology", back: "생리학", desc: "신체 기능을 연구하는 학문 (예시 )" },
    { front: "Homeostasis", back: "항상성", desc: "신체 내부 환경을 일정하게 유지 (예시 )" },
    { front: "Anatomy", back: "해부학", desc: "신체 구조를 연구하는 학문 (예시 )" },
    { front: "Physiology", back: "생리학", desc: "신체 기능을 연구하는 학문 (예시 )" },
    { front: "Homeostasis", back: "항상성", desc: "신체 내부 환경을 일정하게 유지 (예시 )" },
    { front: "Anatomy", back: "해부학", desc: "신체 구조를 연구하는 학문 (예시 )" },
    { front: "Physiology", back: "생리학", desc: "신체 기능을 연구하는 학문 (예시 )" },
    { front: "Homeostasis", back: "항상성", desc: "신체 내부 환경을 일정하게 유지 (예시 )" },
    { front: "Anatomy", back: "해부학", desc: "신체 구조를 연구하는 학문 (예시 )" },
    { front: "Physiology", back: "생리학", desc: "신체 기능을 연구하는 학문 (예시 )" },
    { front: "Homeostasis", back: "항상성", desc: "신체 내부 환경을 일정하게 유지 (예시 )" },
    { front: "Anatomy", back: "해부학", desc: "신체 구조를 연구하는 학문 (예시 )" },
    { front: "Physiology", back: "생리학", desc: "신체 기능을 연구하는 학문 (예시 )" },
    { front: "Homeostasis", back: "항상성", desc: "신체 내부 환경을 일정하게 유지 (예시 )" },
    { front: "Anatomy", back: "해부학", desc: "신체 구조를 연구하는 학문 (예시 )" },
    { front: "Physiology", back: "생리학", desc: "신체 기능을 연구하는 학문 (예시 )" },
  ],
  "세포와조직": [
    { front: "Cell", back: "세포", desc: "생명체의 기본 단위 (예시 )" },
    { front: "Nucleus", back: "핵", desc: "유전 정보를 담는 핵심 기관 (예시 )" },
    { front: "Mitochondria", back: "미토콘드리아", desc: "에너지 생산소 기관 (예시 )" },
    { front: "Cell", back: "세포", desc: "생명체의 기본 단위 (예시 )" },
    { front: "Nucleus", back: "핵", desc: "유전 정보를 담는 핵심 기관 (예시 )" },
    { front: "Mitochondria", back: "미토콘드리아", desc: "에너지 생산소 기관 (예시 )" },
    { front: "Cell", back: "세포", desc: "생명체의 기본 단위 (예시 )" },
    { front: "Nucleus", back: "핵", desc: "유전 정보를 담는 핵심 기관 (예시 )" },
    { front: "Mitochondria", back: "미토콘드리아", desc: "에너지 생산소 기관 (예시 )" },
    { front: "Cell", back: "세포", desc: "생명체의 기본 단위 (예시 )" },
    { front: "Nucleus", back: "핵", desc: "유전 정보를 담는 핵심 기관 (예시 )" },
    { front: "Mitochondria", back: "미토콘드리아", desc: "에너지 생산소 기관 (예시 )" },
    { front: "Cell", back: "세포", desc: "생명체의 기본 단위 (예시 )" },
    { front: "Nucleus", back: "핵", desc: "유전 정보를 담는 핵심 기관 (예시 )" },
    { front: "Mitochondria", back: "미토콘드리아", desc: "에너지 생산소 기관 (예시 )" },
    { front: "Cell", back: "세포", desc: "생명체의 기본 단위 (예시 )" },
    { front: "Nucleus", back: "핵", desc: "유전 정보를 담는 핵심 기관 (예시 )" },
    { front: "Mitochondria", back: "미토콘드리아", desc: "에너지 생산소 기관 (예시 )" },
    { front: "Cell", back: "세포", desc: "생명체의 기본 단위 (예시 )" },
    { front: "Nucleus", back: "핵", desc: "유전 정보를 담는 핵심 기관 (예시 )" },
    { front: "Mitochondria", back: "미토콘드리아", desc: "에너지 생산소 기관 (예시 )" },
    { front: "Cell", back: "세포", desc: "생명체의 기본 단위 (예시 )" },
    { front: "Nucleus", back: "핵", desc: "유전 정보를 담는 핵심 기관 (예시 )" },
    { front: "Mitochondria", back: "미토콘드리아", desc: "에너지 생산소 기관 (예시 )" },
    { front: "Cell", back: "세포", desc: "생명체의 기본 단위 (예시 )" },
    { front: "Nucleus", back: "핵", desc: "유전 정보를 담는 핵심 기관 (예시 )" },
    { front: "Mitochondria", back: "미토콘드리아", desc: "에너지 생산소 기관 (예시 )" },
    { front: "Cell", back: "세포", desc: "생명체의 기본 단위 (예시 )" },
    { front: "Nucleus", back: "핵", desc: "유전 정보를 담는 핵심 기관 (예시 )" },
    { front: "Mitochondria", back: "미토콘드리아", desc: "에너지 생산소 기관 (예시 )" },
    { front: "Cell", back: "세포", desc: "생명체의 기본 단위 (예시 )" },
    { front: "Nucleus", back: "핵", desc: "유전 정보를 담는 핵심 기관 (예시 )" },
    { front: "Mitochondria", back: "미토콘드리아", desc: "에너지 생산소 기관 (예시 )" },
    { front: "Cell", back: "세포", desc: "생명체의 기본 단위 (예시 )" },
    { front: "Nucleus", back: "핵", desc: "유전 정보를 담는 핵심 기관 (예시 )" },
    { front: "Mitochondria", back: "미토콘드리아", desc: "에너지 생산소 기관 (예시 )" },
    { front: "Cell", back: "세포", desc: "생명체의 기본 단위 (예시 )" },
    { front: "Nucleus", back: "핵", desc: "유전 정보를 담는 핵심 기관 (예시 )" },
    { front: "Mitochondria", back: "미토콘드리아", desc: "에너지 생산소 기관 (예시 )" },
    { front: "Cell", back: "세포", desc: "생명체의 기본 단위 (예시 )" },
    { front: "Nucleus", back: "핵", desc: "유전 정보를 담는 핵심 기관 (예시 )" },
    { front: "Mitochondria", back: "미토콘드리아", desc: "에너지 생산소 기관 (예시 )" },
    { front: "Cell", back: "세포", desc: "생명체의 기본 단위 (예시 )" },
    { front: "Nucleus", back: "핵", desc: "유전 정보를 담는 핵심 기관 (예시 )" },
    { front: "Mitochondria", back: "미토콘드리아", desc: "에너지 생산소 기관 (예시 )" },
    { front: "Cell", back: "세포", desc: "생명체의 기본 단위 (예시 )" },
    { front: "Nucleus", back: "핵", desc: "유전 정보를 담는 핵심 기관 (예시 )" },
    { front: "Mitochondria", back: "미토콘드리아", desc: "에너지 생산소 기관 (예시 )" },
    { front: "Cell", back: "세포", desc: "생명체의 기본 단위 (예시 )" },
    { front: "Nucleus", back: "핵", desc: "유전 정보를 담는 핵심 기관 (예시 )" },
  ],
  "뼈대계통": [
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
    { front: "Humerus", back: "상완골", desc: "팔 위쪽 뼈 (예시 )" },
    { front: "Tibia", back: "정강이뼈", desc: "다리 아래쪽의 뼈 (예시 )" },
    { front: "Femur", back: "대퇴골", desc: "가장 긴 다리 뼈 (예시 )" },
  ],
  "관절계통": [
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
    { front: "Ligament", back: "인대", desc: "뼈와 뼈를 연결 (예시 )" },
    { front: "Cartilage", back: "연골", desc: "충격 흡수 조직 (예시 )" },
    { front: "Synovial joint", back: "윤활관절", desc: "움직임이 많은 관절 (예시 )" },
  ],
  "근육계통": [
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
    { front: "Triceps brachii", back: "삼두근", desc: "팔을 펴는 근육 (예시 )" },
    { front: "Skeletal muscle", back: "골격근", desc: "수의적 근육 (예시 )" },
    { front: "Biceps brachii", back: "이두근", desc: "팔을 굽히는 근육 (예시 )" },
  ],
  "신경계통": [
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
    { front: "Cerebrum", back: "대뇌", desc: "인지와 감각 기능 담당 (예시 )" },
    { front: "Spinal cord", back: "척수", desc: "신호 전달 경로 (예시 )" },
    { front: "Neuron", back: "뉴런", desc: "신경계의 기본 단위 (예시 )" },
  ],
};
